config/routes.rb
Telerise::Application.routes.draw do

  resources :comments

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  
  # various ajax routes
  match "/show_video_ajax" => "videos#show_video_ajax"
  match "/hide_video_ajax" => "videos#hide_video_ajax"
  match "/users/check_login" => "users#check_login"
  match "/videos/check_url" => "videos#check_url"
  match "/share_toggle" => "videos#share_toggle"
  
  # sorting video routes
  match "/all-time-best" => "videos#best", :as => :best
  match "/currently-popular" => "videos#currently_popular", :as => :currently_popular
  match "/controversial" => "videos#controversial"
  
  # voting routes
  match "/video_vote_up" => "videos#vote_up"
  match "/video_vote_down" => "videos#vote_down"
  match "/video_remove_vote_up" => "videos#remove_vote_up"
  match "/video_remove_vote_down" => "videos#remove_vote_down"
  match "/video_reverse_vote_up" => "videos#reverse_vote_up"
  match "/video_reverse_vote_down" => "videos#reverse_vote_down"
  
  match "/comment_vote_up" => "comments#vote_up"
  match "/comment_vote_down" => "comments#vote_down"
  match "/comment_remove_vote_up" => "comments#remove_vote_up"
  match "/comment_remove_vote_down" => "comments#remove_vote_down"
  match "/comment_reverse_vote_up" => "comments#reverse_vote_up"
  match "/comment_reverse_vote_down" => "comments#reverse_vote_down"
  
  
  resources :sessions
  resources :users
  resources :videos

  root :to => "videos#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
  has_many :votes, :as => :votable
  attr_accessible :message, :video_id, :user_id
  
  def total_votes
    self.votes_up + self.votes_down
  end
  
  require 'statistics2'
  def ranking
      n = self.votes_up + self.votes_down
      if n == 0
        return 0
      end
      z = 1.281551565545 # 80% confidence
      p = self.votes_up.to_f / n
      left = p + 1/(2*n)*z*z
      right = z * Math.sqrt(p*(1-p)/n + z*z/(4*n*n))
      under = 1+1/n*z*z
      return (left - right) / under
  end
  
  def vote_up(user)
    @vote = Vote.create(:vote => "up", :user_id => user.id, :votable_id => self.id, :votable_type => "Comment")
    self.votes_up = self.votes_up + 1
    self.save!
    self.user.comment_karma = self.user.comment_karma + 1
    self.user.save!
  end
  
  def vote_down(user)
    @vote = Vote.create(:vote => "down", :user_id => user.id, :votable_id => self.id, :votable_type => "Comment")
    self.votes_down = self.votes_down + 1
    self.save!
    self.user.comment_karma = self.user.comment_karma - 1
    self.user.save!
  end
  
  def remove_vote_up(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Comment"]
    @vote.destroy
    self.votes_up = self.votes_up - 1
    self.save!
    self.user.comment_karma = self.user.comment_karma - 1
    self.user.save!
  end
  
  def remove_vote_down(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Comment"]
    @vote.destroy
    self.votes_down = self.votes_down - 1
    self.save!
    self.user.comment_karma = self.user.comment_karma + 1
    self.user.save!
  end
  
  def reverse_vote_up(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Comment"]
    @vote.destroy
    self.votes_up = self.votes_up - 1
    @vote = Vote.create(:vote => "down", :user_id => user.id, :votable_id => self.id, :votable_type => "Comment")
    self.votes_down = self.votes_down + 1
    self.save!
    self.user.comment_karma = self.user.comment_karma - 2
    self.user.save!
  end
  
  def reverse_vote_down(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Comment"]
    @vote.destroy
    self.votes_down = self.votes_down - 1
    @vote = Vote.create(:vote => "up", :user_id => user.id, :votable_id => self.id, :votable_type => "Comment")
    self.votes_up = self.votes_up + 1
    self.save!
    self.user.comment_karma = self.user.comment_karma + 2
    self.user.save!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :current_user_login, :only => :create
  
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])
    @video = Video.find params[:comment][:video_id]
    @comment.user_id = current_user.id
    if @comment.save
      @comment.vote_up(current_user)
      respond_to do |format|
        format.js
        format.html { redirect_to @video }
      end
    else
      redirect_to @video, :notice => "Something went wrong!"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to @comment, :notice  => "Successfully updated comment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @video = @comment.video
    @comment.destroy
    redirect_to @video, :notice => "Successfully deleted comment."
  end
  
  def vote_up
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def vote_down
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.vote_down(current_user)
    respond_to do |format|
      format.js { }
      format.html { redirect_to @video }
    end
  end
  
  def remove_vote_up
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.remove_vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def remove_vote_down
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.remove_vote_down(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def reverse_vote_up
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.reverse_vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def reverse_vote_down
    @comment = Comment.find params[:comment_id]
    @video = @comment.video
    @comment.reverse_vote_down(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/_votes.html.erb
<% if current_user %>

	<% if current_user.voted_for?(comment) %>
	
		<div id="vote_up"><%= link_to '+', comment_remove_vote_up_path(:comment_id => comment.id), :class => 'voted', :remote => true %></div>
		<h5><%= comment.votes_up - comment.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', comment_reverse_vote_up_path(:comment_id => comment.id), :remote => true  %></div>
	
	<% elsif current_user.voted_against?(comment) %>
	
		<div id="vote_up"><%= link_to '+', comment_reverse_vote_down_path(:comment_id => comment.id), :remote => true  %></div>
		<h5><%= comment.votes_up - comment.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', comment_remove_vote_down_path(:comment_id => comment.id), :class => 'voted', :remote => true   %></div>
	
	<% else %>
	
		<div id="vote_up"><%= link_to '+', comment_vote_up_path(:comment_id => comment.id), :remote => true  %></div>
		<h5><%= comment.votes_up - comment.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', comment_vote_down_path(:comment_id => comment.id), :remote => true  %></div>
		
	<% end %>

<% else %>

	<div id="vote_up" class="login"><%= link_to '+', new_session_path %></div>
	<h5><%= comment.votes_up - comment.votes_down %></h5>
	<div id="vote_down" class="login"><%= link_to '-', new_session_path  %></div>

<% end %>

app/views/comments/create.js.erb
$("#comments").prepend("<%= escape_javascript(render :partial => 'videos/comment', :locals => { :comment => @comment} ) %>");
$("#new_comment")[0].reset();
$("#comments_count").html("Comments (<%= @video.comments.count %>)")

app/views/comments/edit.html.erb
<% title "Edit Comment" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @comment %> |
  <%= link_to "View All", comments_path %>
</p>

app/views/comments/index.html.erb
<% title "Comments" %>

<table>
  <tr>
    <th>Message</th>
    <th>Video</th>
    <th>User</th>
  </tr>
  <% for comment in @comments %>
    <tr>
      <td><%= comment.message %></td>
      <td><%= comment.video_id %></td>
      <td><%= comment.user_id %></td>
      <td><%= link_to "Show", comment %></td>
      <td><%= link_to "Edit", edit_comment_path(comment) %></td>
      <td><%= link_to "Destroy", comment, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Comment", new_comment_path %></p>

app/views/comments/new.html.erb
<% title "New Comment" %>

<%= render 'form' %>

<p><%= link_to "Back to List", comments_path %></p>

app/views/comments/remove_vote_down.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");

app/views/comments/remove_vote_up.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");

app/views/comments/reverse_vote_down.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");

app/views/comments/reverse_vote_up.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");

app/views/comments/show.html.erb
<% title "#{@comment.user.login} comment for #{@comment.video.title}" %>
<ul id="comments">
<li>
<div id="<%= @comment.id %>_votes" class="comment_votes video_votes"><%= render :partial => "comments/votes", :locals => { :comment => @comment } %></div>
<div class="comment_data">
	<h4><%= @comment.message %></h4>
	<h5>
		<%= link_to @comment.user.login, user_path(@comment.user) %> 
		<%= time_ago_in_words(@comment.created_at) %> ago <br />
		<%= link_to "video", video_path(@comment.video) %>
		<% if current_user == @comment.user %>
			|  <%= link_to "delete", comment_path(@comment), :method => :delete, :confirm => "Are you sure you want to delete this comment?" %>
		<% end %>
	</h5>
</div>
</li>

app/views/comments/vote_down.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");

app/views/comments/vote_up.js.erb
$("#<%= @comment.id %>_votes").html("<%= escape_javascript(render :partial => 'comments/votes', :locals => { :comment => @comment} ) %>");