config/routes.rb
Telerise::Application.routes.draw do

  resources :comments

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  
  # various ajax routes
  match "/show_video_ajax" => "videos#show_video_ajax"
  match "/hide_video_ajax" => "videos#hide_video_ajax"
  match "/users/check_login" => "users#check_login"
  match "/videos/check_url" => "videos#check_url"
  match "/share_toggle" => "videos#share_toggle"
  
  # sorting video routes
  match "/all-time-best" => "videos#best", :as => :best
  match "/currently-popular" => "videos#currently_popular", :as => :currently_popular
  match "/controversial" => "videos#controversial"
  
  # voting routes
  match "/video_vote_up" => "videos#vote_up"
  match "/video_vote_down" => "videos#vote_down"
  match "/video_remove_vote_up" => "videos#remove_vote_up"
  match "/video_remove_vote_down" => "videos#remove_vote_down"
  match "/video_reverse_vote_up" => "videos#reverse_vote_up"
  match "/video_reverse_vote_down" => "videos#reverse_vote_down"
  
  match "/comment_vote_up" => "comments#vote_up"
  match "/comment_vote_down" => "comments#vote_down"
  match "/comment_remove_vote_up" => "comments#remove_vote_up"
  match "/comment_remove_vote_down" => "comments#remove_vote_down"
  match "/comment_reverse_vote_up" => "comments#reverse_vote_up"
  match "/comment_reverse_vote_down" => "comments#reverse_vote_down"
  
  
  resources :sessions
  resources :users
  resources :videos

  root :to => "videos#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes, :as => :votable
  
  def to_param
    "#{id}-#{title.slice(0..40).gsub(/\W/, '-').downcase.gsub(/-{2,}/,'-')}"
  end
  
  def total_votes
    self.votes_up + self.votes_down
  end
  
  def epoch(date)
    date.to_i
  end
  
  def hot
    s = self.votes_up - self.votes_down
    order = Math.log10(([s.abs, 1].max))
    if s > 0 
      sign = 1
    elsif s < 0
      sign = -1
    else
      sign = 0
    end
    seconds = epoch(self.created_at) - 1134028003
    return (((order + sign) * seconds) /45000).round
  end
  
  def controversial
    return (self.votes_up + self.votes_down).to_f / [(self.votes_up - self.votes_down).abs, 1].max
  end
  
  def best
    return self.votes_up - self.votes_down
  end
  
  def random
    if (c = count) != 0
      find(:first, :offset =>rand(c))
    end
  end
  
  def vote_up(user)
    @vote = Vote.create(:vote => "up", :user_id => user.id, :votable_id => self.id, :votable_type => "Video")
    self.votes_up = self.votes_up + 1
    self.save!
    self.user.video_karma = self.user.video_karma + 1
    self.user.save!
  end
  
  def vote_down(user)
    @vote = Vote.create(:vote => "down", :user_id => user.id, :votable_id => self.id, :votable_type => "Video")
    self.votes_down = self.votes_down + 1
    self.save!
    self.user.video_karma = self.user.video_karma - 1
    self.user.save!
  end
  
  def remove_vote_up(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Video"]
    @vote.destroy
    self.votes_up = self.votes_up - 1
    self.save!
    self.user.video_karma = self.user.video_karma - 1
    self.user.save!
  end
  
  def remove_vote_down(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Video"]
    @vote.destroy
    self.votes_down = self.votes_down - 1
    self.save!
    self.user.video_karma = self.user.video_karma + 1
    self.user.save!
  end
  
  def reverse_vote_up(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Video"]
    @vote.destroy
    self.votes_up = self.votes_up - 1
    @vote = Vote.create(:vote => "down", :user_id => user.id, :votable_id => self.id, :votable_type => "Video")
    self.votes_down = self.votes_down + 1
    self.save!
    self.user.video_karma = self.user.video_karma - 2
    self.user.save!
  end
  
  def reverse_vote_down(user)
    @vote = Vote.first :conditions => [ "user_id = ? AND votable_id = ? AND votable_type = ?", user.id, self.id, "Video"]
    @vote.destroy
    self.votes_down = self.votes_down - 1
    @vote = Vote.create(:vote => "up", :user_id => user.id, :votable_id => self.id, :votable_type => "Video")
    self.votes_up = self.votes_up + 1
    self.save!
    self.user.video_karma = self.user.video_karma + 2
    self.user.save!
  end

  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :current_user_login, :only => :create
  
  def index
    @videos = Video.all.sort_by(&:created_at).reverse
    @videos = Kaminari.paginate_array(@videos).page(params[:page]).per(25)
  end

  def show
    @video = Video.find(params[:id])
    @comment = Comment.new
    @comments = @video.comments.sort_by(&:ranking).reverse
    @videos = Video.all.sort_by(&:hot).reverse
    @next = @videos[ @videos.index(@video) + 1]
    @previous = @videos[ @videos.index(@video) - 1]
    @random = Video.offset(rand(Video.count)).first
  end

  def new
    if current_user
      @video = Video.new
    else
      flash[:error] = "You must be signed in to submit a new video."
      redirect_to root_path
    end
  end

  def create
    api = Embedly::API.new :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; ryan.macinnes@gmail.com)'
    obj = api.oembed :url => params[:video][:url]
    @embedly = obj[0]
    unless @embedly.provider_name == nil 
      @video = Video.new(params[:video])
      @video.user_id = current_user.id
      @video.provider = @embedly.provider_name
      @video.height = @embedly.height
      @video.width = @embedly.width
      @video.embed = @embedly.html
      @video.thumb = @embedly.thumbnail_url
      @video.thumb_height = @embedly.thumbnail_height
      @video.thumb_width = @embedly.thumbnail_width
      if @video.save
        @video.vote_up(current_user)
        redirect_to root_path, :notice => "Successfully submitted video."
      else
        render :action => 'new'
      end
    else
      redirect_to root_path, :notice => "Sorry, you submitted an invalid video url."
    end
  end

  def edit
    @video = Video.find(params[:id])
    unless current_user == @video.user && Time.now < (@video.created_at + 1.hour )
      redirect_to root_path, :notice => "Sorry you can only edit a video up to one hour after submitting it."
    end
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      redirect_to @video, :notice  => "Successfully updated video."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_url, :notice => "Successfully deleted video."
  end
  
  def best
    @videos = Video.all.sort_by(&:best).reverse
    @videos = Kaminari.paginate_array(@videos).page(params[:page]).per(25)
  end
  
  def currently_popular
    @videos = Video.all.sort_by(&:hot).reverse
    @videos = Kaminari.paginate_array(@videos).page(params[:page]).per(25)
  end
  
  def controversial
    @videos = Video.all.sort_by(&:controversial).reverse
    @videos = Kaminari.paginate_array(@videos).page(params[:page]).per(25)
  end
  
  def vote_up
    @video = Video.find params[:video_id]
    @video.vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def vote_down
    @video = Video.find params[:video_id]
    @video.vote_down(current_user)
    respond_to do |format|
      format.js { }
      format.html { redirect_to @video }
    end
  end
  
  def remove_vote_up
    @video = Video.find params[:video_id]
    @video.remove_vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def remove_vote_down
    @video = Video.find params[:video_id]
    @video.remove_vote_down(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def reverse_vote_up
    @video = Video.find params[:video_id]
    @video.reverse_vote_up(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def reverse_vote_down
    @video = Video.find params[:video_id]
    @video.reverse_vote_down(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def show_video_ajax
    @video = Video.find params[:video_id]
    @embed = @video.embed
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def hide_video_ajax
    @video = Video.find params[:video_id]
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
  def check_url
    api = Embedly::API.new :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; ryan.macinnes@gmail.com)'
    obj = api.oembed :url => params[:video][:url]
    @embedly = obj[0]
    respond_to do |format|
      format.json { render :json => @embedly.type == "video" }
    end
  end
  
  def share_toggle
    respond_to do |format|
      format.js
      format.html { redirect_to @video }
    end
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_ads_300x250.html.erb
<div style="float:right;">
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-8909561621860243";
	/* Telerise_300x250 */
	google_ad_slot = "5133970960";
	google_ad_width = 300;
	google_ad_height = 250;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	<br />
	<br />
	<br />
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-8909561621860243";
	/* Telerise_300x250 */
	google_ad_slot = "5133970960";
	google_ad_width = 300;
	google_ad_height = 250;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	<br />
	<br />
	<br />
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-8909561621860243";
	/* Telerise_300x250 */
	google_ad_slot = "5133970960";
	google_ad_width = 300;
	google_ad_height = 250;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>

</div>

<div class="clear"></div>

app/views/videos/_comment.html.erb
<li>
	<div id="<%= comment.id %>_votes" class="comment_votes video_votes"><%= render :partial => "comments/votes", :locals => { :comment => comment } %></div>
	<div class="comment_data">
		<h4><%= comment.message %></h4>
		<h5>
			<%= link_to comment.user.login, user_path(comment.user) %> 
			<%= time_ago_in_words(comment.created_at) %> ago <br />
			<%= link_to 'reply', comment %> | 
			<%= link_to 'permalink', comment %>
			<% if current_user == comment.user %>
				|  <%= link_to "delete", comment_path(comment), :method => :delete, :confirm => "Are you sure you want to delete this comment?" %>
			<% end %>
		</h5>
	</div>
</li>

<div class="clear"></div>

app/views/videos/_video.html.erb
<li id="<%= video.id %>_video">
	<div id="<%= video.id %>_votes" class="video_votes">
		<%= render :partial => "videos/votes", :locals => { :video => video } %>
	</div>
	
	<%= link_to show_video_ajax_path(:video_id => video.id), :remote => true do %>
		<%= image_tag "#{video.thumb}", :height => "75px", :class => "fl small_thumb" %>
	<% end %>
	
	<div class="video_data">
		<h3 id="<%= video.id %>_title">
			<%= link_to "#{video.title}", show_video_ajax_path(:video_id => video.id), :remote => true %>
		</h3>
		
		<p>
			Submitted by: <%= link_to video.user.login, user_path(video.user) %> 
			<%= time_ago_in_words(video.created_at) %> ago
			from <%= link_to "#{video.provider}", video.url, :target => "_blank" %> - 
			<%= link_to "#{pluralize(video.comments.count, "comment")}", video %> - 
			<%= link_to "share", share_toggle_path(:video_id => video.id), :remote => true %>
			<% if current_user == video.user && Time.now < (video.created_at + 1.hour ) %>
				- <%= link_to "edit", edit_video_path(video) %>
			<% end %>
			<% if current_user == video.user %>
				- <%= link_to "delete", video_path(video), :method => :delete, :confirm => "Are you sure you want to delete this video?" %>
			<% end %>
		</p>
		<div class="addthis_toolbox addthis_default_style" style="margin-top:10px;display:none;" id="share_<%= video.id %>">
			<a class="addthis_button_preferred_1" addthis:url="<%= video_url(video)%>"></a>
			<a class="addthis_button_preferred_2" addthis:url="<%= video_url(video)%>"></a>
			<a class="addthis_button_preferred_3" addthis:url="<%= video_url(video)%>"></a>
			<a class="addthis_button_preferred_4" addthis:url="<%= video_url(video)%>"></a>
			<a class="addthis_button_compact" addthis:url="<%= video_url(video)%>"></a>
			<a class="addthis_counter addthis_bubble_style" addthis:url="<%= video_url(video)%>"></a>
		</div>
		<script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4dec161d36779167"></script>
	</div>
	<div class="clear"></div>
</li>

<div class="clear"></div>

app/views/videos/_votes.html.erb
<% if current_user %>

	<% if current_user.voted_for?(video) %>
	
		<div id="vote_up"><%= link_to '+', video_remove_vote_up_path(:video_id => video.id), :class => 'voted', :remote => true %></div>
		<h5><%= video.votes_up - video.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', video_reverse_vote_up_path(:video_id => video.id), :remote => true  %></div>
	
	<% elsif current_user.voted_against?(video) %>
	
		<div id="vote_up"><%= link_to '+', video_reverse_vote_down_path(:video_id => video.id), :remote => true  %></div>
		<h5><%= video.votes_up - video.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', video_remove_vote_down_path(:video_id => video.id), :class => 'voted', :remote => true   %></div>
	
	<% else %>
	
		<div id="vote_up"><%= link_to '+', video_vote_up_path(:video_id => video.id), :remote => true  %></div>
		<h5><%= video.votes_up - video.votes_down %></h5>
		<div id="vote_down"><%= link_to '-', video_vote_down_path(:video_id => video.id), :remote => true  %></div>
		
	<% end %>

<% else %>

	<div id="vote_up" class="login"><%= link_to '+', new_session_path %></div>
	<h5><%= video.votes_up - video.votes_down %></h5>
	<div id="vote_down" class="login"><%= link_to '-', new_session_path  %></div>

<% end %>

app/views/videos/best.html.erb
<% title "All Time Highest Rated Videos" %>

<%= render :partial => 'nav' %>

<ul id="video">
		<%= render @videos %>
</ul>

<%= render :partial => 'ads_300x250' %>

<%= paginate @videos %>

app/views/videos/controversial.html.erb
<% title "Controversial Videos" %>

<%= render :partial => 'nav' %>

<ul id="video">
		<%= render @videos %>
</ul>

<%= render :partial => 'ads_300x250' %>

<%= paginate @videos %>

app/views/videos/currently_popular.html.erb
<% title "Newly Submitted Videos" %>

<%= render :partial => 'nav' %>

<ul id="video">
		<%= render @videos %>
</ul>

<%= render :partial => 'ads_300x250' %>

<%= paginate @videos %>

app/views/videos/edit.html.erb
<% title "Edit Video" %>

<h2>Edit Your Video</h2>

<%= form_for @video do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :style => "height:60px; width:217px;" %>
  </p>
  <p><%= f.submit "Update Video", :class => "button" %></p>
<% end %>

<%= raw(@video.embed) %>

app/views/videos/index.html.erb
<% title "- The best goddammned Videos on the internet" %>

<%= render :partial => 'nav' %>

<ul id="video">
		<%= render @videos %>
</ul>

<%= render :partial => 'ads_300x250' %>

<%= paginate @videos %>

app/views/videos/new.html.erb
<% title "New Video" %>

<h2>Submit A New Video</h2>

<%= render 'form' %>

app/views/videos/new_submissions.html.erb
<% title "Newly Submitted Videos" %>

<%= render :partial => 'nav' %>

<ul id="video">
		<%= render @videos %>
</ul>

<%= render :partial => 'ads_300x250' %>

<%= paginate @videos %>

app/views/videos/show_video_ajax.js.erb
$("#<%= @video.id %>_video").append("<div id='<%= @video.id %>_embed' class='embed'><%= escape_javascript(raw(@embed)) %></div>");
$("#<%= @video.id %>_title").html("<%= escape_javascript(link_to "#{@video.title}", hide_video_ajax_path(:video_id => @video.id), :remote => true) %>");

app/views/videos/vote_down.js.erb
$("#<%= @video.id %>_votes").html("<%= escape_javascript(render :partial => 'votes', :locals => { :video => @video }) %>");

app/views/videos/vote_up.js.erb
$("#<%= @video.id %>_votes").html("<%= escape_javascript(render :partial => 'votes', :locals => { :video => @video }) %>");