config/routes.rb
Telerise::Application.routes.draw do

  resources :comments

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  
  # various ajax routes
  match "/show_video_ajax" => "videos#show_video_ajax"
  match "/hide_video_ajax" => "videos#hide_video_ajax"
  match "/users/check_login" => "users#check_login"
  match "/videos/check_url" => "videos#check_url"
  match "/share_toggle" => "videos#share_toggle"
  
  # sorting video routes
  match "/all-time-best" => "videos#best", :as => :best
  match "/currently-popular" => "videos#currently_popular", :as => :currently_popular
  match "/controversial" => "videos#controversial"
  
  # voting routes
  match "/video_vote_up" => "videos#vote_up"
  match "/video_vote_down" => "videos#vote_down"
  match "/video_remove_vote_up" => "videos#remove_vote_up"
  match "/video_remove_vote_down" => "videos#remove_vote_down"
  match "/video_reverse_vote_up" => "videos#reverse_vote_up"
  match "/video_reverse_vote_down" => "videos#reverse_vote_down"
  
  match "/comment_vote_up" => "comments#vote_up"
  match "/comment_vote_down" => "comments#vote_down"
  match "/comment_remove_vote_up" => "comments#remove_vote_up"
  match "/comment_remove_vote_down" => "comments#remove_vote_down"
  match "/comment_reverse_vote_up" => "comments#reverse_vote_up"
  match "/comment_reverse_vote_down" => "comments#reverse_vote_down"
  
  
  resources :sessions
  resources :users
  resources :videos

  root :to => "videos#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_login.html.erb
<div class="fixed">
	
	<div id="login">
	
		<ul>
			<h2>Sign In / Up with:</h2>
			<li id="facebook"><%= link_to "Facebook", "/auth/facebook" %></li>
			<li id="gmail"><%= link_to "Gmail", "/auth/google" %></li>
			<li id="youtube"><%= link_to "YouTube", "/auth/you_tube" %></li>
			<li id="twitter"><%= link_to "Twitter", "/auth/twitter" %></li>
			<li id="yahoo"><%= link_to "Yahoo!", "/auth/yahoo" %></li>
			<li id="linkedin"><%= link_to "Linkedin", "/auth/linked_in" %></li>
			<li id="foursquare"><%= link_to "Foursquare", "/auth/foursquare" %></li>
			<li id="netflix"><%= link_to "Netflix", "/auth/netflix" %></li>
			<li id="vimeo"><%= link_to "Vimeo", "/auth/vimeo" %></li>
		</ul>
	
	</div>

</div>

app/views/layouts/_nav.html.erb
<nav id="user">
	<% if current_user %>
	<% if current_user.login? %>
  	<h2><%= link_to current_user.login, user_path(current_user) %></h2>
		<ul>
			<li><%= current_user.video_karma %> video karma</li>
			<li><%= current_user.comment_karma %> comment karma</li>
  		<li><%= link_to "sign out", signout_path %></li>
		</ul>
	<% else %>
		<h2><%= link_to "sign up / in", new_user_path %></h2>
	<% end %>
	<% else %>
  	<h2 class="login"><%= link_to "sign up / in", new_session_path %></h2>
	<% end %>
</nav>

app/views/layouts/_new_video.html.erb
<div id="new-video">
	<%= form_for Video.new do |f| %>
		<h2>Add a New Video</h2>
	  <p>
			<%= f.label "Video Link" %><br />
	    <%= f.text_field :url, :placeholder => "Paste Video URL here." %>
	  </p>
	  <p>
			<%= f.label "Title" %><br />
	    <%= f.text_field :title, :placeholder => "Video Title" %>
	  </p>
	  <p>
			<%= f.label "Description" %><br />
	    <%= f.text_area :description, :placeholder => "Video Description", :style => "height:60px; width:217px;" %>
	  </p>
	  <p><%= f.submit "New Video", :class => 'button' %></p>
	<% end %>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
  <title>Telerise <%= content_for?(:title) ? yield(:title) : "" %></title>
  <%= stylesheet_link_tag "css" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" %>
	<%= javascript_include_tag "http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js "%>
	<%= javascript_include_tag "rails.js" %>
	<%= javascript_include_tag "application.js" %>
  <%= csrf_meta_tag %>
	<link rel="icon" type="image/png" href="http://www.telerise.tv/favicon.png">
	<meta name="google-site-verification" content="bMNd7KPaus-17y2GE_t50MPoZpA-MM_uzkSnK4779JA" />
	<meta name="description" content="Telerise: The coolest video sharing site on the interwebs." />
	<meta property="og:title" content="Telerise <%= content_for?(:title) ? yield(:title) : "" %>" />
	<meta property="og:site_name" content="<%= request.url %>" />
	<meta property="og:image" content="http://www.telerise.tv/images/share.png" name="thumb" /> 
	<link rel="image_src" href="http://www.telerise.tv/images/share.png" />
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-18213715-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>

</head>
<body>
	
	<% flash.each do |name, msg| %>
    <%= content_tag :div, raw(msg), :id => "flash_#{name}", :class => "flash" %>
  <% end %>

	<% if current_user %>
		<%= render :partial => 'layouts/new_video'%>
	<% else %>
		<%= render :partial => 'layouts/login'%>
	<% end %>
	
	<div id="container">
		<header>
			<% if current_user %>
				<h2 id="new-video"><%= link_to "submit new video", new_video_path %></h2>
			<% else %>
				<h2 class="login"><%= link_to "submit new video", new_video_path %></h2>
			<% end %>
			<%= render :partial => 'layouts/nav' %>
			<h1><%= link_to "Telerise", root_path %></h1>
		</header>
		<%= yield %>
	</div>
	
	<footer>
		<ul>
			<li>©<%= Time.now.year %> <%= link_to "Telerise", root_path %></li>
			<li><%= link_to_unless_current "Newest", root_path %></li>
			<li><%= link_to_unless_current "Currently Popular", currently_popular_path %></li>
			<li><%= link_to_unless_current "All Time Best", best_path %></li>
			<li><%= link_to_unless_current "Controversial", controversial_path %></li>
		</ul>
	</footer>

</body>
</html>